### ISSUE TITLE
Delete schedule modal displays incorrect text

### ISSUE THREAD

**Issue by Tharlaw** [Eorate/petsrus#103]
When you want to delete a pet schedule, the modal now shows the schedule type id instead of the schedule type name. See screenshot
![delete-schedule-modal-20200814](https://user-images.githubusercontent.com/42702035/90256727-c9a3ec00-de4e-11ea-9c68-0de2f0fc2fd2.png)

**Comment by rodne3** [comment]
HHhhmmm. Not sure if we have bandwidth for this, but we need to have some front end unit tests, unless there was a way to catch in the existing tests we had.

**Comment by Tharlaw** [comment]
> HHhhmmm. Not sure if we have bandwidth for this, but we need to have some front end unit tests, unless there was a way to catch in the existing tests we had.

Yeah. Something we need to look at.

**Comment by rodne3** [comment]
Fixed
